---
title: "291finaldump"
format:
  html:
    embed-resources: true
    code-fold: true
execute: 
  warning: false
  cache: true
---
```{r}
library(Ecdat)
library(tidyverse)
data(HI)
```


```{r}
HI |> ggplot(aes(x= experience, y = whrswk)) + geom_smooth()
```

```{r}
HI |> ggplot(aes(x = region, y = whrswk, fill = whi)) + geom_col()
```

```{r}
HI |> ggplot(aes(x= experience, y = whrswk, color = whi)) + geom_smooth()
```

```{r}
HI |> ggplot(aes(x= education, y = whrswk, fill = whi)) + geom_col()
```

```{r}
HI |> ggplot(aes(x= education, y = whrswk, fill = hhi)) + geom_col()
```

```{r}
HI |> ggplot(aes(x= kidslt6, y = whrswk, fill = hhi)) + geom_col()
```
```{r}
table(HI$region)
```
 
```{r}
HI |>
  group_by(region) |>
  summarize(mean_value = mean(whrswk, na.rm = TRUE))
```

```{r}
table(HI$education)
```

```{r}
#mutate(HI, fulltime = recode(whrswk,`40` < 0,`40` = 1,))
```

```{r}
HI$fulltime <- as.numeric(HI$whrswk >= 40)
HI$fulltime_fac <- factor(HI$fulltime,
                            levels = 0:1,
                            labels = c("Less than 40 Hours", "40 or more"))
table(HI$fulltime_fac)
```

```{r}
table(HI$fulltime_fac, HI$whi)
HI|> ggplot(aes(x=experience, y = whrswk)) + geom_smooth() + facet_wrap(vars(whi))
```

```{r}
HI |> summarise_all(~ sum(is.na(.)))
```

```{r}
anova(whi_model, ed_model, test = "Chisq")
```

